### PR TITLE
[WIP] fix: relpath test correctly handles different OS separator

### LINKED ISSUE #185: Fix tests on windows
Currently tests are failing on Windows due to path differences https://github.com/uPortal-Project/resource-server/runs/3270258766
Tests should be updated to work cross platform

### PR DESCRIPTION
**Pull request by bjagg**
Test was failing on Windows VM causing all PRs to fail

Resolves #185

### CODE REVIEW

**Review by jonathanmtran — APPROVED** [review]

**Comment by bjagg** [comment]
Hey devs, there are more tests failing due to the path separator character. But I am starting to wonder if this code is used to create the relative browser URLs. If that's true, then we should use the slash character rather than use the File.separator character based on OS.

Thoughts?

**Comment by bjagg** [comment]
May need to setup on Windows *gag*

**Comment by bjagg** [comment]
Update: yes this fails because the test compares the xml aggregated name based on MD5 against a static file. I do believe this should be the generic forward-slash for web consumption. Will implement in this way then confirm it works on  Windows machine.

**Comment by bjagg** [comment]
#200 Supersedes this PR. Closing this one.

**Pull request closed without merging**
